### ISSUE TITLE
am having this issue 

### ISSUE THREAD

**Issue by VikingStudios-Z** [MrPowerScripts/reddit-karma-farming-bot#111]
self.username = self.rapi.user.me().name
AttributeError: 'NoneType' object has no attribute 'name'

what to do

**Comment by Xpl0itU** [comment]
You need to put your credentials in the bot

**Comment by VikingStudios-Z** [comment]
I ran sudo ./run_linux.sh menu    , and the bot executes,  i edited the config.... and saved it , after i click the start button , this is the ouput :- 

$ sudo ./run_linux.sh menu                                                                                                                                    
04/01/2021 22:32:55
system is Linux
trying to run the bot
running with menu
info loggin
22:32:59 config root: /home/vikingstudiosz/Desktop/reddit-karma-farming-bot/src/config
22:32:59 repo root: /home/vikingstudiosz/Desktop/reddit-karma-farming-bot
22:32:59 src root: /home/vikingstudiosz/Desktop/reddit-karma-farming-bot/src
22:32:59 REDDIT AUTH CONFIG:
 {
  "reddit_client_id": "",
  "reddit_client_secret": "",
  "reddit_password": "",
  "reddit_username": ""
}
22:32:59 REDDIT CONNFIG:
 {
  "reddit_comment_chance": 0.005,
  "reddit_low_score_threshold": 0,
  "reddit_post_chance": 0.005,
  "reddit_remove_low_scores": 0.002,
  "reddit_reply_to_comment": 0.002,
  "reddit_shadowban_check": 0.002,
  "reddit_sleep_schedule": [
    2,
    4
  ],
  "reddit_sub_list": []
}
22:33:14 COBE CONFIG:
 {
  "cobe_base_dir": "/home/vikingstudiosz/Desktop/reddit-karma-farming-bot/src/bots/reddit/actions/comments",
  "cobe_db_dir": "/home/vikingstudiosz/Desktop/reddit-karma-farming-bot/src/bots/reddit/actions/comments/brains",
  "cobe_main_db": "/home/vikingstudiosz/Desktop/reddit-karma-farming-bot/src/bots/reddit/actions/comments/brains/brain.db",
  "cobe_max_db_size": "300mb",
  "cobe_min_db_size": "50mb"
}
22:33:14 using schedules: [((10, 0), (14, 0)), ((18, 0), (22, 0))]
Traceback (most recent call last):
  File "/home/vikingstudiosz/Desktop/reddit-karma-farming-bot/./src/menu.py", line 52, in <module>
    run()
  File "/home/vikingstudiosz/Desktop/reddit-karma-farming-bot/./src/menu.py", line 49, in run
    ui.main()
  File "/home/vikingstudiosz/Desktop/reddit-karma-farming-bot/src/libs/urwide.py", line 970, in main
    self._ui.run_wrapper( self.run )
  File "/home/vikingstudiosz/Desktop/reddit-karma-farming-bot/.venv/lib/python3.9/site-packages/urwid/display_common.py", line 834, in run_wrapper
    return fn()
  File "/home/vikingstudiosz/Desktop/reddit-karma-farming-bot/src/libs/urwide.py", line 987, in run
    self.loop()
  File "/home/vikingstudiosz/Desktop/reddit-karma-farming-bot/src/libs/urwide.py", line 1033, in loop
    self._doKeyPress(focused, key)
  File "/home/vikingstudiosz/Desktop/reddit-karma-farming-bot/src/libs/urwide.py", line 465, in _doKeyPress
    self._doKeyPress(None, key)
  File "/home/vikingstudiosz/Desktop/reddit-karma-farming-bot/src/libs/urwide.py", line 481, in _doKeyPress
    topwidget.keypress(self._currentSize, key)
  File "/home/vikingstudiosz/Desktop/reddit-karma-farming-bot/.venv/lib/python3.9/site-packages/urwid/container.py", line 1135, in keypress
    return self.body.keypress( (maxcol, remaining), key )
  File "/home/vikingstudiosz/Desktop/reddit-karma-farming-bot/.venv/lib/python3.9/site-packages/urwid/listbox.py", line 968, in keypress
    key = focus_widget.keypress((maxcol,),key)
  File "/home/vikingstudiosz/Desktop/reddit-karma-farming-bot/.venv/lib/python3.9/site-packages/urwid/container.py", line 410, in keypress
    key = self.__super.keypress(size, key)
  File "/home/vikingstudiosz/Desktop/reddit-karma-farming-bot/.venv/lib/python3.9/site-packages/urwid/container.py", line 1626, in keypress
    key = self.focus.keypress(tsize, key)
  File "/home/vikingstudiosz/Desktop/reddit-karma-farming-bot/.venv/lib/python3.9/site-packages/urwid/decoration.py", line 622, in keypress
    return self._original_widget.keypress(maxvals, key)
  File "/home/vikingstudiosz/Desktop/reddit-karma-farming-bot/.venv/lib/python3.9/site-packages/urwid/container.py", line 2316, in keypress
    key = w.keypress((mc,) + size[1:], key)
  File "/home/vikingstudiosz/Desktop/reddit-karma-farming-bot/.venv/lib/python3.9/site-packages/urwid/wimp.py", line 543, in keypress
    self._emit('click')
  File "/home/vikingstudiosz/Desktop/reddit-karma-farming-bot/.venv/lib/python3.9/site-packages/urwid/widget.py", line 461, in _emit
    signals.emit_signal(self, name, self, *args)
  File "/home/vikingstudiosz/Desktop/reddit-karma-farming-bot/.venv/lib/python3.9/site-packages/urwid/signals.py", line 265, in emit
    result |= self._call_callback(callback, user_arg, user_args, args)
  File "/home/vikingstudiosz/Desktop/reddit-karma-farming-bot/.venv/lib/python3.9/site-packages/urwid/signals.py", line 295, in _call_callback
    return bool(callback(*args_to_pass))
  File "/home/vikingstudiosz/Desktop/reddit-karma-farming-bot/src/libs/urwide.py", line 419, in _doPress
    self._handle(event_name, button, *args)
  File "/home/vikingstudiosz/Desktop/reddit-karma-farming-bot/src/libs/urwide.py", line 381, in _handle
    return handler.respond(event_name, widget, *args, **kwargs)
  File "/home/vikingstudiosz/Desktop/reddit-karma-farming-bot/src/libs/urwide.py", line 1214, in respond
    return responder(*args, **kwargs) != FORWARD
  File "/home/vikingstudiosz/Desktop/reddit-karma-farming-bot/./src/menu.py", line 34, in onConfig
    config_menu.run()
  File "/home/vikingstudiosz/Desktop/reddit-karma-farming-bot/src/config/config_menu.py", line 68, in run
    ui.main()
  File "/home/vikingstudiosz/Desktop/reddit-karma-farming-bot/src/libs/urwide.py", line 970, in main
    self._ui.run_wrapper( self.run )
  File "/home/vikingstudiosz/Desktop/reddit-karma-farming-bot/.venv/lib/python3.9/site-packages/urwid/display_common.py", line 834, in run_wrapper
    return fn()
  File "/home/vikingstudiosz/Desktop/reddit-karma-farming-bot/src/libs/urwide.py", line 987, in run
    self.loop()
  File "/home/vikingstudiosz/Desktop/reddit-karma-farming-bot/src/libs/urwide.py", line 1033, in loop
    self._doKeyPress(focused, key)
  File "/home/vikingstudiosz/Desktop/reddit-karma-farming-bot/src/libs/urwide.py", line 465, in _doKeyPress
    self._doKeyPress(None, key)
  File "/home/vikingstudiosz/Desktop/reddit-karma-farming-bot/src/libs/urwide.py", line 481, in _doKeyPress
    topwidget.keypress(self._currentSize, key)
  File "/home/vikingstudiosz/Desktop/reddit-karma-farming-bot/.venv/lib/python3.9/site-packages/urwid/container.py", line 1135, in keypress
    return self.body.keypress( (maxcol, remaining), key )
  File "/home/vikingstudiosz/Desktop/reddit-karma-farming-bot/.venv/lib/python3.9/site-packages/urwid/listbox.py", line 968, in keypress
    key = focus_widget.keypress((maxcol,),key)
  File "/home/vikingstudiosz/Desktop/reddit-karma-farming-bot/.venv/lib/python3.9/site-packages/urwid/container.py", line 410, in keypress
    key = self.__super.keypress(size, key)
  File "/home/vikingstudiosz/Desktop/reddit-karma-farming-bot/.venv/lib/python3.9/site-packages/urwid/container.py", line 1626, in keypress
    key = self.focus.keypress(tsize, key)
  File "/home/vikingstudiosz/Desktop/reddit-karma-farming-bot/.venv/lib/python3.9/site-packages/urwid/decoration.py", line 622, in keypress
    return self._original_widget.keypress(maxvals, key)
  File "/home/vikingstudiosz/Desktop/reddit-karma-farming-bot/.venv/lib/python3.9/site-packages/urwid/container.py", line 2316, in keypress
    key = w.keypress((mc,) + size[1:], key)
  File "/home/vikingstudiosz/Desktop/reddit-karma-farming-bot/.venv/lib/python3.9/site-packages/urwid/wimp.py", line 543, in keypress
    self._emit('click')
  File "/home/vikingstudiosz/Desktop/reddit-karma-farming-bot/.venv/lib/python3.9/site-packages/urwid/widget.py", line 461, in _emit
    signals.emit_signal(self, name, self, *args)
  File "/home/vikingstudiosz/Desktop/reddit-karma-farming-bot/.venv/lib/python3.9/site-packages/urwid/signals.py", line 265, in emit
    result |= self._call_callback(callback, user_arg, user_args, args)
  File "/home/vikingstudiosz/Desktop/reddit-karma-farming-bot/.venv/lib/python3.9/site-packages/urwid/signals.py", line 295, in _call_callback
    return bool(callback(*args_to_pass))
  File "/home/vikingstudiosz/Desktop/reddit-karma-farming-bot/src/libs/urwide.py", line 419, in _doPress
    self._handle(event_name, button, *args)
  File "/home/vikingstudiosz/Desktop/reddit-karma-farming-bot/src/libs/urwide.py", line 381, in _handle
    return handler.respond(event_name, widget, *args, **kwargs)
  File "/home/vikingstudiosz/Desktop/reddit-karma-farming-bot/src/libs/urwide.py", line 1214, in respond
    return responder(*args, **kwargs) != FORWARD
  File "/home/vikingstudiosz/Desktop/reddit-karma-farming-bot/src/config/config_menu.py", line 56, in onSave
    menu.run()
  File "/home/vikingstudiosz/Desktop/reddit-karma-farming-bot/src/menu.py", line 49, in run
    ui.main()
  File "/home/vikingstudiosz/Desktop/reddit-karma-farming-bot/src/libs/urwide.py", line 970, in main
    self._ui.run_wrapper( self.run )
  File "/home/vikingstudiosz/Desktop/reddit-karma-farming-bot/.venv/lib/python3.9/site-packages/urwid/display_common.py", line 834, in run_wrapper
    return fn()
  File "/home/vikingstudiosz/Desktop/reddit-karma-farming-bot/src/libs/urwide.py", line 987, in run
    self.loop()
  File "/home/vikingstudiosz/Desktop/reddit-karma-farming-bot/src/libs/urwide.py", line 1033, in loop
    self._doKeyPress(focused, key)
  File "/home/vikingstudiosz/Desktop/reddit-karma-farming-bot/src/libs/urwide.py", line 465, in _doKeyPress
    self._doKeyPress(None, key)
  File "/home/vikingstudiosz/Desktop/reddit-karma-farming-bot/src/libs/urwide.py", line 481, in _doKeyPress
    topwidget.keypress(self._currentSize, key)
  File "/home/vikingstudiosz/Desktop/reddit-karma-farming-bot/.venv/lib/python3.9/site-packages/urwid/container.py", line 1135, in keypress
    return self.body.keypress( (maxcol, remaining), key )
  File "/home/vikingstudiosz/Desktop/reddit-karma-farming-bot/.venv/lib/python3.9/site-packages/urwid/listbox.py", line 968, in keypress
    key = focus_widget.keypress((maxcol,),key)
  File "/home/vikingstudiosz/Desktop/reddit-karma-farming-bot/.venv/lib/python3.9/site-packages/urwid/container.py", line 410, in keypress
    key = self.__super.keypress(size, key)
  File "/home/vikingstudiosz/Desktop/reddit-karma-farming-bot/.venv/lib/python3.9/site-packages/urwid/container.py", line 1626, in keypress
    key = self.focus.keypress(tsize, key)
  File "/home/vikingstudiosz/Desktop/reddit-karma-farming-bot/.venv/lib/python3.9/site-packages/urwid/decoration.py", line 622, in keypress
    return self._original_widget.keypress(maxvals, key)
  File "/home/vikingstudiosz/Desktop/reddit-karma-farming-bot/.venv/lib/python3.9/site-packages/urwid/container.py", line 2316, in keypress
    key = w.keypress((mc,) + size[1:], key)
  File "/home/vikingstudiosz/Desktop/reddit-karma-farming-bot/.venv/lib/python3.9/site-packages/urwid/wimp.py", line 543, in keypress
    self._emit('click')
  File "/home/vikingstudiosz/Desktop/reddit-karma-farming-bot/.venv/lib/python3.9/site-packages/urwid/widget.py", line 461, in _emit
    signals.emit_signal(self, name, self, *args)
  File "/home/vikingstudiosz/Desktop/reddit-karma-farming-bot/.venv/lib/python3.9/site-packages/urwid/signals.py", line 265, in emit
    result |= self._call_callback(callback, user_arg, user_args, args)
  File "/home/vikingstudiosz/Desktop/reddit-karma-farming-bot/.venv/lib/python3.9/site-packages/urwid/signals.py", line 295, in _call_callback
    return bool(callback(*args_to_pass))
  File "/home/vikingstudiosz/Desktop/reddit-karma-farming-bot/src/libs/urwide.py", line 419, in _doPress
    self._handle(event_name, button, *args)
  File "/home/vikingstudiosz/Desktop/reddit-karma-farming-bot/src/libs/urwide.py", line 381, in _handle
    return handler.respond(event_name, widget, *args, **kwargs)
  File "/home/vikingstudiosz/Desktop/reddit-karma-farming-bot/src/libs/urwide.py", line 1214, in respond
    return responder(*args, **kwargs) != FORWARD
  File "/home/vikingstudiosz/Desktop/reddit-karma-farming-bot/src/menu.py", line 29, in onStarted
    bot.run()
  File "/home/vikingstudiosz/Desktop/reddit-karma-farming-bot/src/bot.py", line 6, in run
    reddit = RedditBot()
  File "/home/vikingstudiosz/Desktop/reddit-karma-farming-bot/src/bots/reddit/bot.py", line 21, in __init__
    self.cleanup = Cleanup()
  File "/home/vikingstudiosz/Desktop/reddit-karma-farming-bot/src/bots/reddit/actions/cleanup_actions.py", line 12, in __init__
    self.username = self.rapi.user.me().name
AttributeError: 'NoneType' object has no attribute 'name'


What should i do abt it?

**Comment by MrPowerScripts** [comment]
you're using an older version. use the latest version. and then check your credentials.
