### ISSUE TITLE
yaml

### ISSUE THREAD

**Issue by HarmonLucifer** [MrPowerScripts/reddit-karma-farming-bot#120]
Hello, everytime I run the windows bat i get this 

Edit: I fixed the Issue now I have this one

Traceback (most recent call last):
  File "./src/init.py", line 4, in <module>
    import bot
  File "C:\Users\Acer\Downloads\Compressed\reddit-karma-farming-bot-master\src\bot.py", line 1, in <module>
    from bots.reddit import RedditBot
  File "C:\Users\Acer\Downloads\Compressed\reddit-karma-farming-bot-master\src\bots\reddit\__init__.py", line 1, in <module>
    from .bot import RedditBot
  File "C:\Users\Acer\Downloads\Compressed\reddit-karma-farming-bot-master\src\bots\reddit\bot.py", line 1, in <module>
    from apis import reddit_api
  File "C:\Users\Acer\Downloads\Compressed\reddit-karma-farming-bot-master\src\apis\__init__.py", line 1, in <module>
    from config import reddit_config
  File "C:\Users\Acer\Downloads\Compressed\reddit-karma-farming-bot-master\src\config\reddit_config.py", line 27, in <module>
    config_gen()
  File "C:\Users\Acer\Downloads\Compressed\reddit-karma-farming-bot-master\src\config\reddit\config_gen.py", line 48, in config_gen
    if authenticated(reddit) is True:
  File "C:\Users\Acer\Downloads\Compressed\reddit-karma-farming-bot-master\src\config\reddit\config_gen.py", line 34, in authenticated
    reddit.user.me()
  File "C:\Users\Acer\.virtualenvs\reddit-karma-farming-bot-master-5y-raNLJ\lib\site-packages\praw\models\user.py", line 134, in me
    user_data = self._reddit.get(API_PATH["me"])
  File "C:\Users\Acer\.virtualenvs\reddit-karma-farming-bot-master-5y-raNLJ\lib\site-packages\praw\reddit.py", line 497, in get
    return self._objectify_request(method="GET", params=params, path=path)
  File "C:\Users\Acer\.virtualenvs\reddit-karma-farming-bot-master-5y-raNLJ\lib\site-packages\praw\reddit.py", line 584, in _objectify_request
    path=path,
  File "C:\Users\Acer\.virtualenvs\reddit-karma-farming-bot-master-5y-raNLJ\lib\site-packages\praw\reddit.py", line 765, in request
    json=json,
  File "C:\Users\Acer\.virtualenvs\reddit-karma-farming-bot-master-5y-raNLJ\lib\site-packages\prawcore\sessions.py", line 339, in request
    url=url,
  File "C:\Users\Acer\.virtualenvs\reddit-karma-farming-bot-master-5y-raNLJ\lib\site-packages\prawcore\sessions.py", line 235, in _request_with_retries
    url,
  File "C:\Users\Acer\.virtualenvs\reddit-karma-farming-bot-master-5y-raNLJ\lib\site-packages\prawcore\sessions.py", line 195, in _make_request
    timeout=timeout,
  File "C:\Users\Acer\.virtualenvs\reddit-karma-farming-bot-master-5y-raNLJ\lib\site-packages\prawcore\rate_limit.py", line 35, in call
    kwargs["headers"] = set_header_callback()
  File "C:\Users\Acer\.virtualenvs\reddit-karma-farming-bot-master-5y-raNLJ\lib\site-packages\prawcore\sessions.py", line 282, in _set_header_callback
    self._authorizer.refresh()
  File "C:\Users\Acer\.virtualenvs\reddit-karma-farming-bot-master-5y-raNLJ\lib\site-packages\prawcore\auth.py", line 356, in refresh
    password=self._password,
  File "C:\Users\Acer\.virtualenvs\reddit-karma-farming-bot-master-5y-raNLJ\lib\site-packages\prawcore\auth.py", line 157, in _request_token
    response, payload["error"], payload.get("error_description")
prawcore.exceptions.OAuthException: invalid_grant error processing request

**Comment by MrPowerScripts** [comment]
wrong crendentials. check and make sure everything is correct in the .env file

**Comment by MrPowerScripts** [comment]
if you  need further support please join the discord server. it is likely not a bug. https://bit.ly/mrps-discord
