### ISSUE TITLE
error?

### ISSUE THREAD

**Issue by HarmonLucifer** [MrPowerScripts/reddit-karma-farming-bot#122]
09:14:07 using schedules: []
Traceback (most recent call last):
  File "C:\Users\Acer\Downloads\Compressed\reddit-karma-farming-bot-master\src\utils.py", line 40, in check_internet
    urllib.request.urlopen(host, None, timeout)
  File "c:\users\acer\appdata\local\programs\python\python37-32\lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "c:\users\acer\appdata\local\programs\python\python37-32\lib\urllib\request.py", line 531, in open
    response = meth(req, response)
  File "c:\users\acer\appdata\local\programs\python\python37-32\lib\urllib\request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "c:\users\acer\appdata\local\programs\python\python37-32\lib\urllib\request.py", line 563, in error
    result = self._call_chain(*args)
  File "c:\users\acer\appdata\local\programs\python\python37-32\lib\urllib\request.py", line 503, in _call_chain
    result = func(*args)
  File "c:\users\acer\appdata\local\programs\python\python37-32\lib\urllib\request.py", line 755, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "c:\users\acer\appdata\local\programs\python\python37-32\lib\urllib\request.py", line 525, in open
    response = self._open(req, data)
  File "c:\users\acer\appdata\local\programs\python\python37-32\lib\urllib\request.py", line 543, in _open
    '_open', req)
  File "c:\users\acer\appdata\local\programs\python\python37-32\lib\urllib\request.py", line 503, in _call_chain
    result = func(*args)
  File "c:\users\acer\appdata\local\programs\python\python37-32\lib\urllib\request.py", line 1360, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "c:\users\acer\appdata\local\programs\python\python37-32\lib\urllib\request.py", line 1320, in do_open
    r = h.getresponse()
  File "c:\users\acer\appdata\local\programs\python\python37-32\lib\http\client.py", line 1336, in getresponse
    response.begin()
  File "c:\users\acer\appdata\local\programs\python\python37-32\lib\http\client.py", line 306, in begin
    version, status, reason = self._read_status()
  File "c:\users\acer\appdata\local\programs\python\python37-32\lib\http\client.py", line 267, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "c:\users\acer\appdata\local\programs\python\python37-32\lib\socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "c:\users\acer\appdata\local\programs\python\python37-32\lib\ssl.py", line 1071, in recv_into
    return self.read(nbytes, buffer)
  File "c:\users\acer\appdata\local\programs\python\python37-32\lib\ssl.py", line 929, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./src/init.py", line 7, in <module>
    if check_internet() is True:
  File "C:\Users\Acer\Downloads\Compressed\reddit-karma-farming-bot-master\src\utils.py", line 43, in check_internet
    log.error(ex.message)
AttributeError: 'timeout' object has no attribute 'message'
exiting...
Press any key to continue . . .

**Comment by MrPowerScripts** [comment]
I've pushed a fix for the error on the latest master. but it failed because it couldn't access reddit.com. you'll need to sort out the connection. If you need further support please join the discord https://bit.ly/mrps-discord.
