### ISSUE TITLE
ModuleNotFoundError: No module named 'Stemmer'

### ISSUE THREAD

**Issue by DasteWasTaken** [MrPowerScripts/reddit-karma-farming-bot#137]
I am trying to run the .bat file but it just says this:
```
Traceback (most recent call last):
  File "C:\Users\daste\Desktop\reddit-karma-farming-bot-master\src\init.py", line 4, in <module>
    import bot
  File "C:\Users\daste\Desktop\reddit-karma-farming-bot-master\src\bot.py", line 1, in <module>
    from bots.reddit import RedditBot
  File "C:\Users\daste\Desktop\reddit-karma-farming-bot-master\src\bots\reddit\__init__.py", line 1, in <module>
    from .bot import RedditBot
  File "C:\Users\daste\Desktop\reddit-karma-farming-bot-master\src\bots\reddit\bot.py", line 5, in <module>
    from bots.reddit.actions.comments.comment_actions import Comments
  File "C:\Users\daste\Desktop\reddit-karma-farming-bot-master\src\bots\reddit\actions\comments\comment_actions.py", line 1, in <module>
    from .sources.cobe import Cobe
  File "C:\Users\daste\Desktop\reddit-karma-farming-bot-master\src\bots\reddit\actions\comments\sources\cobe.py", line 1, in <module>
    from cobe.brain import Brain
  File "C:\Users\daste\.virtualenvs\reddit-karma-farming-bot-master-Oa0UVMUL\lib\site-packages\cobe\brain.py", line 16, in <module>
    from . import tokenizers
  File "C:\Users\daste\.virtualenvs\reddit-karma-farming-bot-master-Oa0UVMUL\lib\site-packages\cobe\tokenizers.py", line 4, in <module>
    import Stemmer
ModuleNotFoundError: No module named 'Stemmer'
exiting...
```
It also says this:
```
Processing c:\users\daste\desktop\reddit-karma-farming-bot-master\deps\windows\pystemmer-2.0.1-cp39-cp39-win_amd64.whl
PyStemmer is already installed with the same version as the provided wheel. Use --force-reinstall to force an installation of the wheel.
Installing dependencies from Pipfile.lock (2dc5ba)...
  ================================ 1/1 - 00:00:00
An error occurred while installing pystemmer==2.0.1 --hash=sha256:9b81c35302f1d2a5ad9465b85986db246990db93d97d3e8f129269ed7102788e! Will try again.
Installing initially failed dependencies...
```
How can I fix this?
I did pip install PyStemmer, but it doesn't help.

**Comment by pog222** [comment]
i got the same error and i fixed it by restarting my computer, i dont know why it does that but restarting or shutting down fixes it for some reason.

**Comment by DasteWasTaken** [comment]
I tried restarting a few times and it still happens :/

**Comment by MrPowerScripts** [comment]
It looks like you've cloned the bot to a virtualenv? You should just close it to a regular directory and then follow the instructions in the docs. the bot creates and manages its own virtualenv. I think running the steps inside of one can cause issues.
