### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'lower'

### ISSUE THREAD

**Issue by client** [MrPowerScripts/reddit-karma-farming-bot#142]
Whenever I try running the bot on windows/linux and it tries reposting a post it just spits this error out. I've redownloaded the code like 4 times and it still happens.
```
Traceback (most recent call last):
  File "./src/init.py", line 10, in <module>
    bot.run()
  File "/root/reddit-karma-farming-bot/src/bot.py", line 8, in run
    reddit.run()
  File "/root/reddit-karma-farming-bot/src/bots/reddit/bot.py", line 62, in run
    self.tick()
  File "/root/reddit-karma-farming-bot/src/bots/reddit/bot.py", line 57, in tick
    action.call()
  File "/root/reddit-karma-farming-bot/src/bots/reddit/actions/post_actions.py", line 70, in repost
    sub = self.rapi.subreddit(self.crosspost(sub.display_name))
  File "/root/reddit-karma-farming-bot/.venv/lib/python3.8/site-packages/praw/models/helpers.py", line 183, in __call__
    lower_name = display_name.lower()
AttributeError: 'NoneType' object has no attribute 'lower'
```

**Comment by client** [comment]
Managed to fix it by defaulting all the values in reddit_config.py.
