### ISSUE TITLE
prawcore.exceptions.Forbidden: received 403 HTTP response exiting... `

### ISSUE THREAD

**Issue by AlexBaldry** [MrPowerScripts/reddit-karma-farming-bot#143]
`Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\reddit-karma-farming-bot-4.0.3\src\init.py", line 10, in <module>
    bot.run()
  File "C:\Users\Administrator\Desktop\reddit-karma-farming-bot-4.0.3\src\bot.py", line 8, in run
    reddit.run()
  File "C:\Users\Administrator\Desktop\reddit-karma-farming-bot-4.0.3\src\bots\reddit\bot.py", line 57, in run
    self.tick()
  File "C:\Users\Administrator\Desktop\reddit-karma-farming-bot-4.0.3\src\bots\reddit\bot.py", line 53, in tick
    action.call()
  File "C:\Users\Administrator\Desktop\reddit-karma-farming-bot-4.0.3\src\bots\reddit\actions\comments\comment_actions.py", line 64, in comment
    comment.reply(self.comments.get_reply(comment.body))
  File "C:\Users\Administrator\.virtualenvs\reddit-karma-farming-bot-4.0.3-AnlWK8Lr\lib\site-packages\praw\models\reddit\mixins\replyable.py", line 38, in reply
    comments = self._reddit.post(API_PATH["comment"], data=data)
  File "C:\Users\Administrator\.virtualenvs\reddit-karma-farming-bot-4.0.3-AnlWK8Lr\lib\site-packages\praw\reddit.py", line 752, in post
    return self._objectify_request(
  File "C:\Users\Administrator\.virtualenvs\reddit-karma-farming-bot-4.0.3-AnlWK8Lr\lib\site-packages\praw\reddit.py", line 666, in _objectify_request
    self.request(
  File "C:\Users\Administrator\.virtualenvs\reddit-karma-farming-bot-4.0.3-AnlWK8Lr\lib\site-packages\praw\reddit.py", line 848, in request
    return self._core.request(
  File "C:\Users\Administrator\.virtualenvs\reddit-karma-farming-bot-4.0.3-AnlWK8Lr\lib\site-packages\prawcore\sessions.py", line 324, in request
    return self._request_with_retries(
  File "C:\Users\Administrator\.virtualenvs\reddit-karma-farming-bot-4.0.3-AnlWK8Lr\lib\site-packages\prawcore\sessions.py", line 260, in _request_with_retries
    raise self.STATUS_EXCEPTIONS[response.status_code](response)
prawcore.exceptions.Forbidden: received 403 HTTP response
exiting... `

**Comment by MrPowerScripts** [comment]
403 is an auth issue. Recheck all the values in the `.env` file. Something is likely wrong there.

**Comment by elonwtf** [comment]
I've reinstalled the bot and deleted and made the script again. 

Error: https://pastebin.com/zhmmzC7U
