### ISSUE TITLE
session problem

### ISSUE THREAD

**Issue by vhraa** [MrPowerScripts/reddit-karma-farming-bot#166]
i have no idea what to do. i've putted in the correct credentials

Traceback (most recent call last):
  File "D:\Downloads\reddit-karma-farming-bot-master\src\init.py", line 4, in <module>
    import bot
  File "D:\Downloads\reddit-karma-farming-bot-master\src\bot.py", line 1, in <module>
    from bots.reddit import RedditBot
  File "D:\Downloads\reddit-karma-farming-bot-master\src\bots\reddit\__init__.py", line 1, in <module>
    from .bot import RedditBot
  File "D:\Downloads\reddit-karma-farming-bot-master\src\bots\reddit\bot.py", line 1, in <module>
    from apis import reddit_api
  File "D:\Downloads\reddit-karma-farming-bot-master\src\apis\__init__.py", line 1, in <module>
    from config import reddit_config
  File "D:\Downloads\reddit-karma-farming-bot-master\src\config\reddit_config.py", line 23, in <module>
    config_gen()
  File "D:\Downloads\reddit-karma-farming-bot-master\src\config\reddit\config_gen.py", line 46, in config_gen
    if authenticated(reddit) is True:
  File "D:\Downloads\reddit-karma-farming-bot-master\src\config\reddit\config_gen.py", line 32, in authenticated
    reddit.user.me()
  File "C:\Users\vhrag\.virtualenvs\reddit-karma-farming-bot-master-QIfxKKqy\lib\site-packages\praw\models\user.py", line 155, in me
    user_data = self._reddit.get(API_PATH["me"])
  File "C:\Users\vhrag\.virtualenvs\reddit-karma-farming-bot-master-QIfxKKqy\lib\site-packages\praw\reddit.py", line 566, in get
    return self._objectify_request(method="GET", params=params, path=path)
  File "C:\Users\vhrag\.virtualenvs\reddit-karma-farming-bot-master-QIfxKKqy\lib\site-packages\praw\reddit.py", line 667, in _objectify_request
    self.request(
  File "C:\Users\vhrag\.virtualenvs\reddit-karma-farming-bot-master-QIfxKKqy\lib\site-packages\praw\reddit.py", line 849, in request
    return self._core.request(
  File "C:\Users\vhrag\.virtualenvs\reddit-karma-farming-bot-master-QIfxKKqy\lib\site-packages\prawcore\sessions.py", line 328, in request
    return self._request_with_retries(
  File "C:\Users\vhrag\.virtualenvs\reddit-karma-farming-bot-master-QIfxKKqy\lib\site-packages\prawcore\sessions.py", line 251, in _request_with_retries
    return self._do_retry(
  File "C:\Users\vhrag\.virtualenvs\reddit-karma-farming-bot-master-QIfxKKqy\lib\site-packages\prawcore\sessions.py", line 160, in _do_retry
    return self._request_with_retries(
  File "C:\Users\vhrag\.virtualenvs\reddit-karma-farming-bot-master-QIfxKKqy\lib\site-packages\prawcore\sessions.py", line 251, in _request_with_retries
    return self._do_retry(
  File "C:\Users\vhrag\.virtualenvs\reddit-karma-farming-bot-master-QIfxKKqy\lib\site-packages\prawcore\sessions.py", line 160, in _do_retry
    return self._request_with_retries(
  File "C:\Users\vhrag\.virtualenvs\reddit-karma-farming-bot-master-QIfxKKqy\lib\site-packages\prawcore\sessions.py", line 226, in _request_with_retries
    response, saved_exception = self._make_request(
  File "C:\Users\vhrag\.virtualenvs\reddit-karma-farming-bot-master-QIfxKKqy\lib\site-packages\prawcore\sessions.py", line 183, in _make_request
    response = self._rate_limiter.call(
  File "C:\Users\vhrag\.virtualenvs\reddit-karma-farming-bot-master-QIfxKKqy\lib\site-packages\prawcore\rate_limit.py", line 33, in call
    kwargs["headers"] = set_header_callback()
  File "C:\Users\vhrag\.virtualenvs\reddit-karma-farming-bot-master-QIfxKKqy\lib\site-packages\prawcore\sessions.py", line 281, in _set_header_callback
    self._authorizer.refresh()
  File "C:\Users\vhrag\.virtualenvs\reddit-karma-farming-bot-master-QIfxKKqy\lib\site-packages\prawcore\auth.py", line 379, in refresh
    self._request_token(
  File "C:\Users\vhrag\.virtualenvs\reddit-karma-farming-bot-master-QIfxKKqy\lib\site-packages\prawcore\auth.py", line 155, in _request_token
    response = self._authenticator._post(url, **data)
  File "C:\Users\vhrag\.virtualenvs\reddit-karma-farming-bot-master-QIfxKKqy\lib\site-packages\prawcore\auth.py", line 30, in _post
    response = self._requestor.request(
  File "C:\Users\vhrag\.virtualenvs\reddit-karma-farming-bot-master-QIfxKKqy\lib\site-packages\prawcore\requestor.py", line 56, in request
    raise RequestException(exc, args, kwargs)
prawcore.exceptions.RequestException: error with request HTTPSConnectionPool(host='www.reddit.com', port=443): Max retries exceeded with url: /api/v1/access_token (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1129)')))
exiting...
Press any key to continue . . .

**Comment by MrPowerScripts** [comment]
I don't think this is an issue with the bot. if anything it's likely an issue with the environment. make sure you're SSL libraries are up to date.
