### ISSUE TITLE
Modules not working

### ISSUE THREAD

**Issue by Brandonbr1** [MrPowerScripts/reddit-karma-farming-bot#168]
getting this error:
Traceback (most recent call last):
  File "C:\Users\Brandon J Mohammed\Downloads\reddit-karma-farming-bot-master\reddit-karma-farming-bot-master\src\init.py", line 4, in <module>
    import bot
  File "C:\Users\Brandon J Mohammed\Downloads\reddit-karma-farming-bot-master\reddit-karma-farming-bot-master\src\bot.py", line 1, in <module>
    from bots.reddit import RedditBot
  File "C:\Users\Brandon J Mohammed\Downloads\reddit-karma-farming-bot-master\reddit-karma-farming-bot-master\src\bots\reddit\__init__.py", line 1, in <module>
    from .bot import RedditBot
  File "C:\Users\Brandon J Mohammed\Downloads\reddit-karma-farming-bot-master\reddit-karma-farming-bot-master\src\bots\reddit\bot.py", line 1, in <module>
    from apis import reddit_api
  File "C:\Users\Brandon J Mohammed\Downloads\reddit-karma-farming-bot-master\reddit-karma-farming-bot-master\src\apis\__init__.py", line 1, in <module>
    from config import reddit_config
  File "C:\Users\Brandon J Mohammed\Downloads\reddit-karma-farming-bot-master\reddit-karma-farming-bot-master\src\config\reddit_config.py", line 23, in <module>
    config_gen()
  File "C:\Users\Brandon J Mohammed\Downloads\reddit-karma-farming-bot-master\reddit-karma-farming-bot-master\src\config\reddit\config_gen.py", line 46, in config_gen
    if authenticated(reddit) is True:
  File "C:\Users\Brandon J Mohammed\Downloads\reddit-karma-farming-bot-master\reddit-karma-farming-bot-master\src\config\reddit\config_gen.py", line 32, in authenticated
    reddit.user.me()
  File "C:\Users\Brandon J Mohammed\.virtualenvs\reddit-karma-farming-bot-master-XAJlfS4l\lib\site-packages\praw\models\user.py", line 162, in me
    user_data = self._reddit.get(API_PATH["me"])
  File "C:\Users\Brandon J Mohammed\.virtualenvs\reddit-karma-farming-bot-master-XAJlfS4l\lib\site-packages\praw\reddit.py", line 573, in get
    return self._objectify_request(method="GET", params=params, path=path)
  File "C:\Users\Brandon J Mohammed\.virtualenvs\reddit-karma-farming-bot-master-XAJlfS4l\lib\site-packages\praw\reddit.py", line 674, in _objectify_request
    self.request(
  File "C:\Users\Brandon J Mohammed\.virtualenvs\reddit-karma-farming-bot-master-XAJlfS4l\lib\site-packages\praw\reddit.py", line 856, in request
    return self._core.request(
  File "C:\Users\Brandon J Mohammed\.virtualenvs\reddit-karma-farming-bot-master-XAJlfS4l\lib\site-packages\prawcore\sessions.py", line 330, in request
    return self._request_with_retries(
  File "C:\Users\Brandon J Mohammed\.virtualenvs\reddit-karma-farming-bot-master-XAJlfS4l\lib\site-packages\prawcore\sessions.py", line 228, in _request_with_retries
    response, saved_exception = self._make_request(
  File "C:\Users\Brandon J Mohammed\.virtualenvs\reddit-karma-farming-bot-master-XAJlfS4l\lib\site-packages\prawcore\sessions.py", line 185, in _make_request
    response = self._rate_limiter.call(
  File "C:\Users\Brandon J Mohammed\.virtualenvs\reddit-karma-farming-bot-master-XAJlfS4l\lib\site-packages\prawcore\rate_limit.py", line 33, in call
    kwargs["headers"] = set_header_callback()
  File "C:\Users\Brandon J Mohammed\.virtualenvs\reddit-karma-farming-bot-master-XAJlfS4l\lib\site-packages\prawcore\sessions.py", line 283, in _set_header_callback
    self._authorizer.refresh()
  File "C:\Users\Brandon J Mohammed\.virtualenvs\reddit-karma-farming-bot-master-XAJlfS4l\lib\site-packages\prawcore\auth.py", line 425, in refresh
    self._request_token(
  File "C:\Users\Brandon J Mohammed\.virtualenvs\reddit-karma-farming-bot-master-XAJlfS4l\lib\site-packages\prawcore\auth.py", line 158, in _request_token
    raise OAuthException(
prawcore.exceptions.OAuthException: invalid_grant error processing request
exiting...

**Comment by MrPowerScripts** [comment]
This is an auth issue. you probably entered the wrong credentials into the bot. delete the folder, clone it again, and follow the docs closely. it should resolve whatever  the auth issue is.
