### ISSUE TITLE
Error while posting

### ISSUE THREAD

**Issue by elonwtf** [MrPowerScripts/reddit-karma-farming-bot#174]
`00:14:29 running action: reddit_post_chance
00:14:29 running repost
00:14:29 finding a post to re-post
00:14:29 picking a random subreddit
00:14:29 checking subreddit: forhonor
00:14:29 searching post in sub: forhonor
00:14:29 pushshift-url: https://api.pushshift.io/reddit/search/submission/?subreddit=forhonor&before=1599257669&after=1599171269&score>=5000&limit=1
00:14:29 reposting post: im3p5r
Traceback (most recent call last):
  File "C:\Users\Administrator\Downloads\reddit-karma-farming-bot-4.0.3\reddit-karma-farming-bot-4.0.3\src\init.py", line 10, in <module>
    bot.run()
  File "C:\Users\Administrator\Downloads\reddit-karma-farming-bot-4.0.3\reddit-karma-farming-bot-4.0.3\src\bot.py", line 8, in run
    reddit.run()
  File "C:\Users\Administrator\Downloads\reddit-karma-farming-bot-4.0.3\reddit-karma-farming-bot-4.0.3\src\bots\reddit\bot.py", line 57, in run
    self.tick()
  File "C:\Users\Administrator\Downloads\reddit-karma-farming-bot-4.0.3\reddit-karma-farming-bot-4.0.3\src\bots\reddit\bot.py", line 53, in tick
    action.call()
  File "C:\Users\Administrator\Downloads\reddit-karma-farming-bot-4.0.3\reddit-karma-farming-bot-4.0.3\src\bots\reddit\actions\post_actions.py", line 70, in repost
    sub = self.rapi.subreddit(self.crosspost(sub.display_name))
  File "C:\Users\Administrator\.virtualenvs\reddit-karma-farming-bot-4.0.3-qiPPEft8\lib\site-packages\praw\models\helpers.py", line 186, in __call__
    lower_name = display_name.lower()
AttributeError: 'NoneType' object has no attribute 'lower'
exiting...
Press any key to continue . . .`

**Comment by MrPowerScripts** [comment]
`display_name.lower() AttributeError: 'NoneType' object has no attribute` I think this is reffering to your reddit account username. so it probably isn't set properly somewhere in the config. maybe check the `.env` file. see if you can get it set properly. or delete the bot folder and start over, making sure you follow the guided instructions where it's asking for your information.

**Comment by elonwtf** [comment]
Will give it a try. Why not start the discord back up and get moderators to moderate it?

**Comment by MrPowerScripts** [comment]
I may bring it back with a small monthly petreon donation required to communicate. I think some small financial barrier would prevent a lot of the trolls and drama seekers that made it less fun to manage. and there will be more incentive to maintain the quality of discourse I wanted.. it's a lot of work. bringing in mods doesn't simply make it easier, because then you have to coach and train them on how you want matters to be handled. and I don't want to offload that effort onto random strangers for free. like, what do they get out of that? having to deal with the drama for me? that's silly. especially since the people who have the most time to moderate are kids and they should be spending their time on more constructive things. I'm not sure of the most sustainable way to bring it back online, but I have thought about it.

**Comment by elonwtf** [comment]
I think a patreon donation would be amazing and is such a good idea. It would definitely prevent trolls and drama seekers because of the paywall. I doubt they will troll etc if they've paid for it.
