### ISSUE TITLE
Couldn't find any posts - skipping reposting for now

### ISSUE THREAD

**Issue by MysticalEnnio** [MrPowerScripts/reddit-karma-farming-bot#181]
16:04:52 couldn't find any posts - skipping reposting for now                                                           

Traceback (most recent call last):                                                                                        File "C:\Users\Mystical_Ennio\Downloads\reddit-karma-farming-bot-master\src\init.py", line 10, in <module>                bot.run()                                                                                                             File "C:\Users\Mystical_Ennio\Downloads\reddit-karma-farming-bot-master\src\bot.py", line 8, in run                       reddit.run()                                                                                                          File "C:\Users\Mystical_Ennio\Downloads\reddit-karma-farming-bot-master\src\bots\reddit\bot.py", line 63, in run          self.tick()                                                                                                           File "C:\Users\Mystical_Ennio\Downloads\reddit-karma-farming-bot-master\src\bots\reddit\bot.py", line 58, in tick         action.call()                                                                                                         File "C:\Users\Mystical_Ennio\Downloads\reddit-karma-farming-bot-master\src\bots\reddit\actions\post_actions.py", line 96, in repost                                                                                                              api_call=requests.get(post.url).status_code                                                                         AttributeError: 'NoneType' object has no attribute 'url'                                                                exiting...

When I run the bot sometimes this error comes and I need to exit...
Can anyone help?

**Comment by MrPowerScripts** [comment]
yep that sounds like a solid solution

**Comment by sheepsushis** [comment]
@MrPowerScripts has this been merged yet?
