### ISSUE TITLE
error after 12 minutes of running

### ISSUE THREAD

**Issue by devins-07** [MrPowerScripts/reddit-karma-farming-bot#182]
13:20:03 picking a random subreddit
13:20:03 checking subreddit: MoneroMining
13:20:04 replying to comment
13:22:00 935279366216 < 0.005 = True
running action: reddit_post_chance
13:22:00 running repost
13:22:00 finding a post to re-post
13:22:00 picking a random subreddit
13:22:00 checking subreddit: Hawaii
13:22:00 searching post in sub: Hawaii
13:22:00 pushshift-url: https://api.pushshift.io/reddit/search/submission/?subreddit=Hawaii&before=1602609720&after=1602523320&score>=5000&limit=1&author!=[deleted]&selftext:not=[deleted]
pushshift http error: 500
13:22:30 669509669938 < 0.002 = True
running action: reddit_remove_low_scores
13:22:30 checking for low score content to remove
13:22:30 no low score content to clean up. I'm a good bot! :^)
13:22:43 747271725725 < 0.005 = True
running action: reddit_post_chance
13:22:43 running repost
13:22:43 finding a post to re-post
13:22:43 picking a random subreddit
13:22:43 checking subreddit: gamernews
13:22:43 searching post in sub: gamernews
13:22:43 pushshift-url: https://api.pushshift.io/reddit/search/submission/?subreddit=gamernews&before=1602609763&after=1602523363&score>=5000&limit=1&author!=[deleted]&selftext:not=[deleted]
Traceback (most recent call last):
  File "C:\Users\devin\.virtualenvs\reddit-karma-farming-bot-master-FR336Gl1\lib\site-packages\urllib3\connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\devin\.virtualenvs\reddit-karma-farming-bot-master-FR336Gl1\lib\site-packages\urllib3\connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "C:\Users\devin\.virtualenvs\reddit-karma-farming-bot-master-FR336Gl1\lib\site-packages\urllib3\connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Users\devin\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 1368, in getresponse
    response.begin()
  File "C:\Users\devin\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 317, in begin
    version, status, reason = self._read_status()
  File "C:\Users\devin\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 286, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\devin\.virtualenvs\reddit-karma-farming-bot-master-FR336Gl1\lib\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "C:\Users\devin\.virtualenvs\reddit-karma-farming-bot-master-FR336Gl1\lib\site-packages\urllib3\connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "C:\Users\devin\.virtualenvs\reddit-karma-farming-bot-master-FR336Gl1\lib\site-packages\urllib3\util\retry.py", line 532, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "C:\Users\devin\.virtualenvs\reddit-karma-farming-bot-master-FR336Gl1\lib\site-packages\urllib3\packages\six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\devin\.virtualenvs\reddit-karma-farming-bot-master-FR336Gl1\lib\site-packages\urllib3\connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\devin\.virtualenvs\reddit-karma-farming-bot-master-FR336Gl1\lib\site-packages\urllib3\connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "C:\Users\devin\.virtualenvs\reddit-karma-farming-bot-master-FR336Gl1\lib\site-packages\urllib3\connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Users\devin\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 1368, in getresponse
    response.begin()
  File "C:\Users\devin\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 317, in begin
    version, status, reason = self._read_status()
  File "C:\Users\devin\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 286, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\devin\Documents\reddit-karma-farming-bot-master\src\init.py", line 10, in <module>
    bot.run()
  File "C:\Users\devin\Documents\reddit-karma-farming-bot-master\src\bot.py", line 8, in run
    reddit.run()
  File "C:\Users\devin\Documents\reddit-karma-farming-bot-master\src\bots\reddit\bot.py", line 63, in run
    self.tick()
  File "C:\Users\devin\Documents\reddit-karma-farming-bot-master\src\bots\reddit\bot.py", line 58, in tick
    action.call()
  File "C:\Users\devin\Documents\reddit-karma-farming-bot-master\src\bots\reddit\actions\post_actions.py", line 96, in repost
    api_call=requests.get(post.url).status_code
  File "C:\Users\devin\.virtualenvs\reddit-karma-farming-bot-master-FR336Gl1\lib\site-packages\requests\api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\devin\.virtualenvs\reddit-karma-farming-bot-master-FR336Gl1\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\devin\.virtualenvs\reddit-karma-farming-bot-master-FR336Gl1\lib\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\devin\.virtualenvs\reddit-karma-farming-bot-master-FR336Gl1\lib\site-packages\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\devin\.virtualenvs\reddit-karma-farming-bot-master-FR336Gl1\lib\site-packages\requests\adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
exiting...
Press any key to continue . . .

**Comment by johanviper972** [comment]
Thanks, I didn't know about code blocks sorry :s 
Actually, it's been like this for me for 2 days now. Relaunching the bot doesn't really solve it...

**Comment by sheepsushis** [comment]
Download the bot 2x on 2 different folders, and you might need to use a VPN/Proxy but im not too sure. @johanviper972

**Comment by johanviper972** [comment]
Got it, thanks

**Comment by synaptium** [comment]
> Got it, thanks @sheepsushis

where you able to run this severally on one pc?
