### ISSUE TITLE
i get his error

### ISSUE THREAD

**Issue by TheHolyTachanka** [MrPowerScripts/reddit-karma-farming-bot#185]
Python found!
Found VS 2019 Build Tools - Excellent
Found PyStemmer
Pipenv found!
ERROR: PyStemmer-2.0.1-cp39-cp39-win_amd64.whl is not a supported wheel on this platform.
Installing dependencies from Pipfile.lock (48156f)...
  ================================ 0/0 - 00:00:00
To activate this project's virtualenv, run pipenv shell.
Alternatively, run a command inside the virtualenv with pipenv run.
running without menu
info loggin
02:50:19 config root: C:\Users\Nikolai\Desktop\reddit-karma-farming-bot-master\src\config
02:50:19 repo root: C:\Users\Nikolai\Desktop\reddit-karma-farming-bot-master
02:50:19 src root: C:\Users\Nikolai\Desktop\reddit-karma-farming-bot-master\src
please input your account client id :secret
please input your account client secret :client secret
please input your account password :password
please input your account username :username
Traceback (most recent call last):
  File "C:\Users\Nikolai\Desktop\reddit-karma-farming-bot-master\src\init.py", line 4, in <module>
    import bot
  File "C:\Users\Nikolai\Desktop\reddit-karma-farming-bot-master\src\bot.py", line 1, in <module>
    from bots.reddit import RedditBot
  File "C:\Users\Nikolai\Desktop\reddit-karma-farming-bot-master\src\bots\reddit\__init__.py", line 1, in <module>
    from .bot import RedditBot
  File "C:\Users\Nikolai\Desktop\reddit-karma-farming-bot-master\src\bots\reddit\bot.py", line 1, in <module>
    from apis import reddit_api
  File "C:\Users\Nikolai\Desktop\reddit-karma-farming-bot-master\src\apis\__init__.py", line 1, in <module>
    from config import reddit_config
  File "C:\Users\Nikolai\Desktop\reddit-karma-farming-bot-master\src\config\reddit_config.py", line 23, in <module>
    config_gen()
  File "C:\Users\Nikolai\Desktop\reddit-karma-farming-bot-master\src\config\reddit\config_gen.py", line 46, in config_gen
    if authenticated(reddit) is True:
  File "C:\Users\Nikolai\Desktop\reddit-karma-farming-bot-master\src\config\reddit\config_gen.py", line 32, in authenticated
    reddit.user.me()
  File "C:\Users\Nikolai\.virtualenvs\reddit-karma-farming-bot-master-7v21uN1D\lib\site-packages\praw\models\user.py", line 162, in me
    user_data = self._reddit.get(API_PATH["me"])
  File "C:\Users\Nikolai\.virtualenvs\reddit-karma-farming-bot-master-7v21uN1D\lib\site-packages\praw\reddit.py", line 573, in get
    return self._objectify_request(method="GET", params=params, path=path)
  File "C:\Users\Nikolai\.virtualenvs\reddit-karma-farming-bot-master-7v21uN1D\lib\site-packages\praw\reddit.py", line 674, in _objectify_request
    self.request(
  File "C:\Users\Nikolai\.virtualenvs\reddit-karma-farming-bot-master-7v21uN1D\lib\site-packages\praw\reddit.py", line 856, in request
    return self._core.request(
  File "C:\Users\Nikolai\.virtualenvs\reddit-karma-farming-bot-master-7v21uN1D\lib\site-packages\prawcore\sessions.py", line 330, in request
    return self._request_with_retries(
  File "C:\Users\Nikolai\.virtualenvs\reddit-karma-farming-bot-master-7v21uN1D\lib\site-packages\prawcore\sessions.py", line 228, in _request_with_retries
    response, saved_exception = self._make_request(
  File "C:\Users\Nikolai\.virtualenvs\reddit-karma-farming-bot-master-7v21uN1D\lib\site-packages\prawcore\sessions.py", line 185, in _make_request
    response = self._rate_limiter.call(
  File "C:\Users\Nikolai\.virtualenvs\reddit-karma-farming-bot-master-7v21uN1D\lib\site-packages\prawcore\rate_limit.py", line 33, in call
    kwargs["headers"] = set_header_callback()
  File "C:\Users\Nikolai\.virtualenvs\reddit-karma-farming-bot-master-7v21uN1D\lib\site-packages\prawcore\sessions.py", line 283, in _set_header_callback
    self._authorizer.refresh()
  File "C:\Users\Nikolai\.virtualenvs\reddit-karma-farming-bot-master-7v21uN1D\lib\site-packages\prawcore\auth.py", line 425, in refresh
    self._request_token(
  File "C:\Users\Nikolai\.virtualenvs\reddit-karma-farming-bot-master-7v21uN1D\lib\site-packages\prawcore\auth.py", line 158, in _request_token
    raise OAuthException(
prawcore.exceptions.OAuthException: invalid_grant error processing request
exiting...
Press any key to continue
obviously i filled out the secret and etc

**Comment by konsteva** [comment]
It is most probably an incompatibility with your version of Python. I had the same issue and I resolved it by creating a virtual environment with Python 3.9 and run "run_windows" from there. In more detail open cmd and write the following commands:

`conda create --name your_env_name python=3.9`  
`conda activate your_env_name`
`cd path_to_the_file` (in your case from what I see the path is C:\Users\Nikolai\Desktop\reddit-karma-farming-bot-master)
`run_windows`

**Comment by MrPowerScripts** [comment]
@konsteva is likely correct. You probably don't have Python 3.9 installed. I haven't used conda but maybe that will work. if not, just try installing python 3.9 directly.
