### ISSUE TITLE
I get this error after I input my account details

### ISSUE THREAD

**Issue by Alo3zera** [MrPowerScripts/reddit-karma-farming-bot#188]
ERROR: PyStemmer-2.0.1-cp39-cp39-win_amd64.whl is not a supported wheel on this platform.
Installing dependencies from Pipfile.lock (48156f)...
  ================================ 0/0 - 00:00:00
To activate this project's virtualenv, run pipenv shell.
Alternatively, run a command inside the virtualenv with pipenv run.
running without menu
Loading .env environment variables...
Traceback (most recent call last):
  File "C:\Users\Casper\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Casper\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Casper\AppData\Local\Programs\Python\Python310\Scripts\pipenv.exe\__main__.py", line 7, in <module>
  File "C:\Users\Casper\AppData\Local\Programs\Python\Python310\lib\site-packages\pipenv\vendor\click\core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\Casper\AppData\Local\Programs\Python\Python310\lib\site-packages\pipenv\vendor\click\core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "C:\Users\Casper\AppData\Local\Programs\Python\Python310\lib\site-packages\pipenv\vendor\click\core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\Casper\AppData\Local\Programs\Python\Python310\lib\site-packages\pipenv\vendor\click\core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\Casper\AppData\Local\Programs\Python\Python310\lib\site-packages\pipenv\vendor\click\core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\Casper\AppData\Local\Programs\Python\Python310\lib\site-packages\pipenv\vendor\click\decorators.py", line 84, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "C:\Users\Casper\AppData\Local\Programs\Python\Python310\lib\site-packages\pipenv\vendor\click\core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\Casper\AppData\Local\Programs\Python\Python310\lib\site-packages\pipenv\cli\command.py", line 413, in run
    do_run(
  File "C:\Users\Casper\AppData\Local\Programs\Python\Python310\lib\site-packages\pipenv\core.py", line 2495, in do_run
    run_fn(*run_args, **run_kwargs)
  File "C:\Users\Casper\AppData\Local\Programs\Python\Python310\lib\site-packages\pipenv\core.py", line 2410, in do_run_nt
    p = _launch_windows_subprocess(script, env)
  File "C:\Users\Casper\AppData\Local\Programs\Python\Python310\lib\site-packages\pipenv\core.py", line 2400, in _launch_windows_subprocess
    return subprocess.Popen([command] + script.args, **options)
  File "C:\Users\Casper\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 966, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\Casper\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 1435, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
TypeError: environment can only contain strings

**Comment by Alo3zera** [comment]
UPDATE:

I tried running this using Ubuntu as well, which resulted in this error:

system is Linux 
Trying to run the bot 
Running without menu
 Loading .env environment variables... 
Traceback (most recent call last):
File "/usr/local/bin/pipenv", line 8, in <module> sys.exit(cli()) File "/usr/local/lib/python3.8/dist-packages/pipenv/vendor/click/core.py", line 1128, in __call__ return self.main(*args, **kwargs) 

File "/usr/local/lib/python3.8/dist-packages/pipenv/vendor/click/core.py", line 1053, in main rv = self.invoke(ctx) 

File "/usr/local/lib/python3.8/dist-packages/pipenv/vendor/click/core.py", line 1659, in invoke return _process_result(sub_ctx.command.invoke(sub_ctx)) 

File "/usr/local/lib/python3.8/dist-packages/pipenv/vendor/click/core.py", line 1395, in invoke return ctx.invoke(self.callback, **ctx.params) File "/usr/local/lib/python3.8/dist-packages/pipenv/vendor/click/core.py", line 754, in invoke return __callback(*args, **kwargs) 

File "/usr/local/lib/python3.8/dist-packages/pipenv/vendor/click/decorators.py", line 84, in new_func return ctx.invoke(f, obj, *args, **kwargs) 

File "/usr/local/lib/python3.8/dist-packages/pipenv/vendor/click/core.py", line 754, in invoke return __callback(*args, **kwargs) 

File "/usr/local/lib/python3.8/dist-packages/pipenv/cli/command.py", line 413, in run do_run( File "/usr/local/lib/python3.8/dist-packages/pipenv/core.py", line 2495, in do_run run_fn(*run_args, **run_kwargs) 

File "/usr/local/lib/python3.8/dist-packages/pipenv/core.py", line 2442, in do_run_posix os.execve( 

TypeError: expected str, bytes or os.PathLike object, not NoneType

**Comment by Alo3zera** [comment]
UPDATE 2:

Tried running this using docker as well, but resulted in the exact error as above...

**Comment by opp** [comment]
@Alo3zera i'm also seeing this issue. did you ever find a solution for this?
