### ISSUE TITLE
No praw

### ISSUE THREAD

**Issue by Cycilism** [MrPowerScripts/reddit-karma-farming-bot#193]
Listen im a retard but how do i get Praw? 

Python found!
Found VS 2019 Build Tools - Excellent
Found PyStemmer
running without menu
info loggin
21:00:19 config root: C:\Users\Diseri\Desktop\reddit-karma-farming-bot-4.0.3\src\config
21:00:19 repo root: C:\Users\Diseri\Desktop\reddit-karma-farming-bot-4.0.3
21:00:19 src root: C:\Users\Diseri\Desktop\reddit-karma-farming-bot-4.0.3\src
Traceback (most recent call last):
  File "C:\Users\Diseri\Desktop\reddit-karma-farming-bot-4.0.3\src\init.py", line 4, in <module>
    import bot
  File "C:\Users\Diseri\Desktop\reddit-karma-farming-bot-4.0.3\src\bot.py", line 1, in <module>
    from bots.reddit import RedditBot
  File "C:\Users\Diseri\Desktop\reddit-karma-farming-bot-4.0.3\src\bots\reddit\__init__.py", line 1, in <module>
    from .bot import RedditBot
  File "C:\Users\Diseri\Desktop\reddit-karma-farming-bot-4.0.3\src\bots\reddit\bot.py", line 1, in <module>
    from apis import reddit_api
  File "C:\Users\Diseri\Desktop\reddit-karma-farming-bot-4.0.3\src\apis\__init__.py", line 1, in <module>
    from config import reddit_config
  File "C:\Users\Diseri\Desktop\reddit-karma-farming-bot-4.0.3\src\config\reddit_config.py", line 5, in <module>
    from config.reddit.config_gen import config_gen
  File "C:\Users\Diseri\Desktop\reddit-karma-farming-bot-4.0.3\src\config\reddit\config_gen.py", line 2, in <module>
    import praw
ModuleNotFoundError: No module named 'praw'
exiting...
Press any key to continue . . .

**Comment by Travis-Owens** [comment]
https://praw.readthedocs.io/en/stable/getting_started/installation.html

Have you looked at this?

**Comment by Cycilism** [comment]
Yes , i did "pip install praw" but it still does not work

**Comment by geeks121** [comment]
pipenv install praw
