### ISSUE TITLE
Database is locked

### ISSUE THREAD

**Issue by pavs94** [MrPowerScripts/reddit-karma-farming-bot#61]
On first run, getting this error: 
```
2020-06-22 02:20:04,591 INFO learn(59) looping through submissions
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 263, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/ps/reddit-test/reddit-karma-farming-bot/src/run.py", line 1, in <module>
    import init
  File "/Users/ps/reddit-test/reddit-karma-farming-bot/src/init.py", line 5, in <module>
    import reddit
  File "/Users/ps/reddit-test/reddit-karma-farming-bot/src/reddit.py", line 12, in <module>
    import bot
  File "/Users/ps/reddit-test/reddit-karma-farming-bot/src/bot.py", line 10, in <module>
    base_brain = Brain(MAIN_DB)
  File "/Users/ps/reddit-test/reddit-karma-farming-bot/venv/lib/python3.8/site-packages/cobe/brain.py", line 47, in __init__
    version = graph.get_info_text("version")
  File "/Users/ps/reddit-test/reddit-karma-farming-bot/venv/lib/python3.8/site-packages/cobe/brain.py", line 505, in get_info_text
    row = c.execute(q, (attribute,)).fetchone()
sqlite3.OperationalError: database is locked
```

**Comment by MrPowerScripts** [comment]
If you need support to run the bot please join us on discord https://bit.ly/mrps-discord I don't like troubleshooting from issues

**Comment by corryalpha** [comment]
ok
