### ISSUE TITLE
The pip file and the pipfile.lock isnt updated with imgur libraries causing the errors to come up

### ISSUE THREAD

**Issue by psywarrior1998** [MrPowerScripts/reddit-karma-farming-bot#65]
```
2020-07-11T06:30:18.857453+00:00 app[worker.1]: info loggin
2020-07-11T06:30:18.866553+00:00 app[worker.1]: Traceback (most recent call last):
2020-07-11T06:30:18.866559+00:00 app[worker.1]:   File "./src/run.py", line 1, in <module>
2020-07-11T06:30:18.866774+00:00 app[worker.1]:     import init
2020-07-11T06:30:18.866800+00:00 app[worker.1]:   File "/app/src/init.py", line 5, in <module>
2020-07-11T06:30:18.867004+00:00 app[worker.1]:     import reddit
2020-07-11T06:30:18.867030+00:00 app[worker.1]:   File "/app/src/reddit.py", line 11, in <module>
2020-07-11T06:30:18.867185+00:00 app[worker.1]:     import bot
2020-07-11T06:30:18.867190+00:00 app[worker.1]:   File "/app/src/bot.py", line 7, in <module>
2020-07-11T06:30:18.867316+00:00 app[worker.1]:     from utils import MAIN_DB
2020-07-11T06:30:18.867319+00:00 app[worker.1]:   File "/app/src/utils.py", line 13, in <module>
2020-07-11T06:30:18.867446+00:00 app[worker.1]:     from imgurpython import ImgurClient
2020-07-11T06:30:18.867497+00:00 app[worker.1]: ModuleNotFoundError: No module named 'imgurpython'
```

**Comment by MrPowerScripts** [comment]
It should be fixed now. can you try it?

**Comment by psywarrior1998** [comment]
it is done now, also it is showing waiting for network atm is it normal?

**Comment by MrPowerScripts** [comment]
hmmm waiting for network i'm not sure. never saw that

**Comment by psywarrior1998** [comment]
2020-07-11T09:18:04.627700+00:00 app[worker.1]: info loggin
2020-07-11T09:18:04.639912+00:00 app[worker.1]: Traceback (most recent call last):
2020-07-11T09:18:04.639966+00:00 app[worker.1]:   File "./src/run.py", line 1, in <module>
2020-07-11T09:18:04.640378+00:00 app[worker.1]:     import init
2020-07-11T09:18:04.640410+00:00 app[worker.1]:   File "/app/src/init.py", line 5, in <module>
2020-07-11T09:18:04.640732+00:00 app[worker.1]:     import reddit
2020-07-11T09:18:04.640762+00:00 app[worker.1]:   File "/app/src/reddit.py", line 11, in <module>
2020-07-11T09:18:04.641088+00:00 app[worker.1]:     import bot
2020-07-11T09:18:04.641120+00:00 app[worker.1]:   File "/app/src/bot.py", line 7, in <module>
2020-07-11T09:18:04.641429+00:00 app[worker.1]:     from utils import MAIN_DB
2020-07-11T09:18:04.641461+00:00 app[worker.1]:   File "/app/src/utils.py", line 13, in <module>
2020-07-11T09:18:04.641803+00:00 app[worker.1]:     from imgurpython import ImgurClient
2020-07-11T09:18:04.641963+00:00 app[worker.1]: ModuleNotFoundError: No module named 'imgurpython'

its coming again still on heroku

**Comment by MrPowerScripts** [comment]
did you re-deploy the app? you have to start it over

**Comment by psywarrior1998** [comment]
yes I clicked  the link again and made a new app

**Comment by MrPowerScripts** [comment]
this is fixed now. please redeploy the app.
