### ISSUE TITLE
Database disk image is malformed

### ISSUE THREAD

**Issue by Memo58Memo** [MrPowerScripts/reddit-karma-farming-bot#97]
I always get this error while I let the but learning:
`database disk image is malformed`

I never touched something in the source. I just edited the utils.py & settings.py

I just started in newly on Windows 10 Ubuntu TLS "sub-system" using via the cmd bash command

Error exactly:

`2020-12-24 00:06:16,376 INFO init(71)
          THE BOT IS WORKING. IT WILL TAKE ABOUT 8 HOURS FOR IT TO LEARN AND START COMMENTING.

2020-12-24 00:06:16,379 INFO init(72) fast learning
2020-12-24 00:06:16,379 INFO learn(63) checking submission
2020-12-24 00:06:16,381 INFO learn(13) trying to learn
2020-12-24 00:06:16,384 INFO learn(17) db size: 2.56640625
2020-12-24 00:06:16,386 INFO learn(35) SUBREDDIT_LIST is active
2020-12-24 00:06:16,388 INFO learn(36) learning from: comedyheaven
2020-12-24 00:06:16,389 INFO learn(54) active db : /mnt/c/Users/root/reddit-karma-farming-bot/src/brains/comedyheaven.db
2020-12-24 00:06:16,394 INFO learn(59) looping through submissions
2020-12-24 00:06:16,823 INFO learn(63) checking submission
2020-12-24 00:06:17,818 INFO learn(63) checking submission
2020-12-24 00:06:18,106 INFO learn(63) checking submission
2020-12-24 00:06:19,225 INFO learn(63) checking submission
2020-12-24 00:06:19,519 INFO learn(63) checking submission
2020-12-24 00:06:21,384 INFO learn(63) checking submission
2020-12-24 00:06:25,658 INFO learn(63) checking submission
2020-12-24 00:06:26,954 INFO learn(63) checking submission
2020-12-24 00:06:27,474 INFO learn(102) database disk image is malformed
Traceback (most recent call last):
  File "/mnt/c/Users/root/reddit-karma-farming-bot/src/learn.py", line 92, in learn
    comment_body.encode("utf8")
  File "/mnt/c/Users/root/reddit-karma-farming-bot/venv/lib/python3.6/site-packages/cobe/brain.py", line 125, in learn
    self._learn_tokens(tokens)
  File "/mnt/c/Users/root/reddit-karma-farming-bot/venv/lib/python3.6/site-packages/cobe/brain.py", line 180, in _learn_tokens
    stemmer=self.stemmer)
  File "/mnt/c/Users/root/reddit-karma-farming-bot/venv/lib/python3.6/site-packages/cobe/brain.py", line 530, in get_token_by_text
    row = c.execute(q, (text,)).fetchone()
sqlite3.DatabaseError: database disk image is malformed
2020-12-24 00:06:27,489 INFO init(75) new db size: 2.5234375
2020-12-24 00:06:27,495 INFO countdown(358) sleeping: 2 seconds
2020-12-24 00:06:27,543 INFO learn(63) checking submission
2020-12-24 00:06:27,864 INFO learn(99) done learning
2020-12-24 00:06:27,872 INFO init(75) new db size: 1.7265625
2020-12-24 00:06:27,882 INFO countdown(358) sleeping: 2 seconds`

**Comment by Memo58Memo** [comment]
New error after restart: 

`2020-12-24 00:39:35,910 INFO learn(102) disk I/O error`

**Comment by Memo58Memo** [comment]
lol 3rd new error, now the db size is not going up

`Traceback (most recent call last):
  File "/mnt/c/Users/root/reddit-karma-farming-bot/src/learn.py", line 92, in learn
    comment_body.encode("utf8")
  File "/mnt/c/Users/root/reddit-karma-farming-bot/venv/lib/python3.6/site-packages/cobe/brain.py", line 125, in learn
    self._learn_tokens(tokens)
  File "/mnt/c/Users/root/reddit-karma-farming-bot/venv/lib/python3.6/site-packages/cobe/brain.py", line 191, in _learn_tokens
    self.graph.add_edge(prev_id, next_id, has_space)
  File "/mnt/c/Users/root/reddit-karma-farming-bot/venv/lib/python3.6/site-packages/cobe/brain.py", line 648, in add_edge
    c.execute(update_q, args)
sqlite3.IntegrityError: UNIQUE constraint failed: edges.next_node, edges.prev_node, edges.has_space, edges.count`

**Comment by kgbprofile** [comment]
Try deleting it's /src/brains. Does the error go away>

**Comment by Memo58Memo** [comment]
> 
> 
> Try deleting it's /src/brains. Does the error go away?

Deleted the dictonary brains,because there is no file inside, I will edit if it works

**Comment by kgbprofile** [comment]
Do you get the same result if you clone the project to another directory and start anew?

**Comment by Memo58Memo** [comment]
it worked now, but my db size is  0.046875 MB  (got the information from localhost site). It started with the size of 0.046 but in the settings the minimum size is 50mb (standard)

**Comment by MrPowerScripts** [comment]
this should all be resolved in the upcoming 4.0 release. try the rkfb4 branch for a previewe
